/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HospitalityRouteImport } from './routes/hospitality'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCafeStatusRouteImport } from './routes/admin.cafe-status'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminEventCategoriesRouteImport } from './routes/admin.event-categories'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminMenuCategoriesRouteImport } from './routes/admin.menu-categories'
import { Route as AdminMenuItemsRouteImport } from './routes/admin.menu-items'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPrayerRequestsRouteImport } from './routes/admin.prayer-requests'
import { Route as PPageKeyRouteImport } from './routes/p.$pageKey'
import { Route as AdminPagesIndexRouteImport } from './routes/admin.pages.index'
import { Route as AdminPagesPageKeyRouteImport } from './routes/admin.pages.$pageKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalityRoute = HospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCafeStatusRoute = AdminCafeStatusRouteImport.update({
  id: '/cafe-status',
  path: '/cafe-status',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventCategoriesRoute = AdminEventCategoriesRouteImport.update({
  id: '/event-categories',
  path: '/event-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuCategoriesRoute = AdminMenuCategoriesRouteImport.update({
  id: '/menu-categories',
  path: '/menu-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuItemsRoute = AdminMenuItemsRouteImport.update({
  id: '/menu-items',
  path: '/menu-items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrayerRequestsRoute = AdminPrayerRequestsRouteImport.update({
  id: '/prayer-requests',
  path: '/prayer-requests',
  getParentRoute: () => AdminRoute,
} as any)
const PPageKeyRoute = PPageKeyRouteImport.update({
  id: '/p/$pageKey',
  path: '/p/$pageKey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminPagesPageKeyRoute = AdminPagesPageKeyRouteImport.update({
  id: '/$pageKey',
  path: '/$pageKey',
  getParentRoute: () => AdminPagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRoute
  '/hospitality': typeof HospitalityRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/prayer': typeof PrayerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visit': typeof VisitRoute
  '/admin/cafe-status': typeof AdminCafeStatusRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/event-categories': typeof AdminEventCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/menu-categories': typeof AdminMenuCategoriesRoute
  '/admin/menu-items': typeof AdminMenuItemsRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/prayer-requests': typeof AdminPrayerRequestsRoute
  '/p/$pageKey': typeof PPageKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pages/$pageKey': typeof AdminPagesPageKeyRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/hospitality': typeof HospitalityRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/prayer': typeof PrayerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visit': typeof VisitRoute
  '/admin/cafe-status': typeof AdminCafeStatusRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/event-categories': typeof AdminEventCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/menu-categories': typeof AdminMenuCategoriesRoute
  '/admin/menu-items': typeof AdminMenuItemsRoute
  '/admin/prayer-requests': typeof AdminPrayerRequestsRoute
  '/p/$pageKey': typeof PPageKeyRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pages/$pageKey': typeof AdminPagesPageKeyRoute
  '/admin/pages': typeof AdminPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRoute
  '/hospitality': typeof HospitalityRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/prayer': typeof PrayerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visit': typeof VisitRoute
  '/admin/cafe-status': typeof AdminCafeStatusRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/event-categories': typeof AdminEventCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/menu-categories': typeof AdminMenuCategoriesRoute
  '/admin/menu-items': typeof AdminMenuItemsRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/prayer-requests': typeof AdminPrayerRequestsRoute
  '/p/$pageKey': typeof PPageKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pages/$pageKey': typeof AdminPagesPageKeyRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/events'
    | '/hospitality'
    | '/login'
    | '/menu'
    | '/prayer'
    | '/sitemap.xml'
    | '/visit'
    | '/admin/cafe-status'
    | '/admin/customers'
    | '/admin/event-categories'
    | '/admin/events'
    | '/admin/homepage'
    | '/admin/menu-categories'
    | '/admin/menu-items'
    | '/admin/pages'
    | '/admin/prayer-requests'
    | '/p/$pageKey'
    | '/admin/'
    | '/admin/pages/$pageKey'
    | '/admin/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/hospitality'
    | '/login'
    | '/menu'
    | '/prayer'
    | '/sitemap.xml'
    | '/visit'
    | '/admin/cafe-status'
    | '/admin/customers'
    | '/admin/event-categories'
    | '/admin/events'
    | '/admin/homepage'
    | '/admin/menu-categories'
    | '/admin/menu-items'
    | '/admin/prayer-requests'
    | '/p/$pageKey'
    | '/admin'
    | '/admin/pages/$pageKey'
    | '/admin/pages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/events'
    | '/hospitality'
    | '/login'
    | '/menu'
    | '/prayer'
    | '/sitemap.xml'
    | '/visit'
    | '/admin/cafe-status'
    | '/admin/customers'
    | '/admin/event-categories'
    | '/admin/events'
    | '/admin/homepage'
    | '/admin/menu-categories'
    | '/admin/menu-items'
    | '/admin/pages'
    | '/admin/prayer-requests'
    | '/p/$pageKey'
    | '/admin/'
    | '/admin/pages/$pageKey'
    | '/admin/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  EventsRoute: typeof EventsRoute
  HospitalityRoute: typeof HospitalityRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  PrayerRoute: typeof PrayerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisitRoute: typeof VisitRoute
  PPageKeyRoute: typeof PPageKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitality': {
      id: '/hospitality'
      path: '/hospitality'
      fullPath: '/hospitality'
      preLoaderRoute: typeof HospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cafe-status': {
      id: '/admin/cafe-status'
      path: '/cafe-status'
      fullPath: '/admin/cafe-status'
      preLoaderRoute: typeof AdminCafeStatusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/event-categories': {
      id: '/admin/event-categories'
      path: '/event-categories'
      fullPath: '/admin/event-categories'
      preLoaderRoute: typeof AdminEventCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-categories': {
      id: '/admin/menu-categories'
      path: '/menu-categories'
      fullPath: '/admin/menu-categories'
      preLoaderRoute: typeof AdminMenuCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-items': {
      id: '/admin/menu-items'
      path: '/menu-items'
      fullPath: '/admin/menu-items'
      preLoaderRoute: typeof AdminMenuItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prayer-requests': {
      id: '/admin/prayer-requests'
      path: '/prayer-requests'
      fullPath: '/admin/prayer-requests'
      preLoaderRoute: typeof AdminPrayerRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/p/$pageKey': {
      id: '/p/$pageKey'
      path: '/p/$pageKey'
      fullPath: '/p/$pageKey'
      preLoaderRoute: typeof PPageKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/pages/$pageKey': {
      id: '/admin/pages/$pageKey'
      path: '/$pageKey'
      fullPath: '/admin/pages/$pageKey'
      preLoaderRoute: typeof AdminPagesPageKeyRouteImport
      parentRoute: typeof AdminPagesRoute
    }
  }
}

interface AdminPagesRouteChildren {
  AdminPagesPageKeyRoute: typeof AdminPagesPageKeyRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesPageKeyRoute: AdminPagesPageKeyRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminRouteChildren {
  AdminCafeStatusRoute: typeof AdminCafeStatusRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEventCategoriesRoute: typeof AdminEventCategoriesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminMenuCategoriesRoute: typeof AdminMenuCategoriesRoute
  AdminMenuItemsRoute: typeof AdminMenuItemsRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminPrayerRequestsRoute: typeof AdminPrayerRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCafeStatusRoute: AdminCafeStatusRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEventCategoriesRoute: AdminEventCategoriesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminMenuCategoriesRoute: AdminMenuCategoriesRoute,
  AdminMenuItemsRoute: AdminMenuItemsRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminPrayerRequestsRoute: AdminPrayerRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  EventsRoute: EventsRoute,
  HospitalityRoute: HospitalityRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  PrayerRoute: PrayerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisitRoute: VisitRoute,
  PPageKeyRoute: PPageKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
